version: '3'
services:
  terraform:
    build: ./terraform
    working_dir: /terraform
    env_file: .env
    volumes:
      - "./terraform:/terraform"
      - "~/.aws/credentials:/root/.aws/credentials"
